// Generated by React Router

import 'react-router';

declare module 'react-router' {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  '/': {
    params: {};
  };
  '/sign-in': {
    params: {};
  };
  '/sign-up': {
    params: {};
  };
  '/pricing': {
    params: {};
  };
  '/app/*': {
    params: {
      '*': string;
    };
  };
};

type RouteFiles = {
  'root.tsx': {
    id: 'root';
    page: '/' | '/sign-in' | '/sign-up' | '/pricing' | '/app/*';
  };
  './landing.tsx': {
    id: 'landing';
    page: '/';
  };
  './signin.tsx': {
    id: 'signin';
    page: '/sign-in';
  };
  './signup.tsx': {
    id: 'signup';
    page: '/sign-up';
  };
  './pricing.tsx': {
    id: 'pricing';
    page: '/pricing';
  };
  './app.tsx': {
    id: 'app';
    page: '/app/*';
  };
};

type RouteModules = {
  root: typeof import('./app/root.tsx');
  landing: typeof import('./app/./landing.tsx');
  signin: typeof import('./app/./signin.tsx');
  signup: typeof import('./app/./signup.tsx');
  pricing: typeof import('./app/./pricing.tsx');
  app: typeof import('./app/./app.tsx');
};
